"""changed_table_content

Revision ID: 064cfe540a72
Revises: 7588a77f34e8
Create Date: 2020-07-26 18:53:13.512451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '064cfe540a72'
down_revision = '7588a77f34e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('api_id', sa.String(length=255), nullable=False))
    op.add_column('game', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('game', sa.Column('modified_at', sa.DateTime(), nullable=False))
    op.drop_constraint('game_ibfk_1', 'game', type_='foreignkey')
    op.drop_column('game', 'user_id')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('modified_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'modified_at')
    op.drop_column('user', 'created_at')
    op.add_column('game', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_ibfk_1', 'game', 'user', ['user_id'], ['id'])
    op.drop_column('game', 'modified_at')
    op.drop_column('game', 'created_at')
    op.drop_column('game', 'api_id')
    # ### end Alembic commands ###
