"""Changed about me size

Revision ID: 0b16d0433f10
Revises: 5d13efef79e4
Create Date: 2021-02-09 18:21:14.034253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b16d0433f10'
down_revision = '5d13efef79e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', mysql.TEXT(), nullable=True))
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
