"""changed

Revision ID: 1c882f5d40d7
Revises: 78f0ae02aae9
Create Date: 2020-09-15 08:20:36.456363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c882f5d40d7'
down_revision = '78f0ae02aae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('initial_release_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'initial_release_date')
    # ### end Alembic commands ###
