"""changed_table_content

Revision ID: 26da43369bd1
Revises: 064cfe540a72
Create Date: 2020-07-26 19:27:30.327307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26da43369bd1'
down_revision = '064cfe540a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_game_timestamp', table_name='game')
    op.drop_column('game', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_game_timestamp', 'game', ['timestamp'], unique=False)
    # ### end Alembic commands ###
