"""changed similar_games to json

Revision ID: 3676a6cb24c3
Revises: 
Create Date: 2021-02-16 06:55:18.601260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3676a6cb24c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('similar_games', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'similar_games')
    # ### end Alembic commands ###
