"""Added user_game tables

Revision ID: 4a11bb603dd8
Revises: edb42950657e
Create Date: 2020-08-11 00:14:18.763575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a11bb603dd8'
down_revision = 'edb42950657e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_game', 'platform', ['platform_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_game', type_='foreignkey')
    op.drop_column('user_game', 'platform_id')
    # ### end Alembic commands ###
