"""changed

Revision ID: 78f0ae02aae9
Revises: 125ea978ddc8
Create Date: 2020-09-11 09:22:46.507891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f0ae02aae9'
down_revision = '125ea978ddc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('developer', sa.String(length=255), nullable=True))
    op.add_column('game', sa.Column('publisher', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'game', ['image_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='unique')
    op.drop_column('game', 'publisher')
    op.drop_column('game', 'developer')
    # ### end Alembic commands ###
