"""Added note

Revision ID: 967e2826ae1a
Revises: ee149440a5b0
Create Date: 2021-01-27 13:21:47.894609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967e2826ae1a'
down_revision = 'ee149440a5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game', 'note')
    # ### end Alembic commands ###
