"""Changed about me size

Revision ID: b68446337ef6
Revises: 0b16d0433f10
Create Date: 2021-02-12 10:14:19.239342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b68446337ef6'
down_revision = '0b16d0433f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('similar_games', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'similar_games')
    # ### end Alembic commands ###
