"""Added user_game table

Revision ID: d078d97c2667
Revises: a551442872ad
Create Date: 2020-08-03 00:28:28.352481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd078d97c2667'
down_revision = 'a551442872ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clear_status', sa.Enum('PLAYING', 'CLEARED', 'FULL_CLEARED', name='gamestatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game')
    # ### end Alembic commands ###
