"""Added user_game tables

Revision ID: edb42950657e
Revises: 15b1e6077ab1
Create Date: 2020-08-05 16:40:01.844713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edb42950657e'
down_revision = '15b1e6077ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('platform', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
