"""Added summary

Revision ID: ee149440a5b0
Revises: 1c882f5d40d7
Create Date: 2020-12-31 00:22:59.255248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee149440a5b0'
down_revision = '1c882f5d40d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'summary')
    # ### end Alembic commands ###
